version: '3'

services:
  git-server:
    image: crbroughton/git-server:latest
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - ~/git-server/keys:/git-server/keys
    - ~/git-server/repos:/git-server/repos
  cgit-server:
    image: emarcs/nginx-cgit
    restart: always
    container_name: cgit-server
    ports:
      - "8000:80"
    volumes:
      - ~/git-server/repos:/srv/git

